name: Build and Push

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fountain-coach/fountainai-typesense  # must be lowercase!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $REGISTRY/$IMAGE_NAME:latest
